/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/Campfire 3D Model.glb -t -o campfire-new.tsx -k 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    campfire: THREE.Mesh;
  };
  materials: {
    None: THREE.MeshStandardMaterial;
  };
};

export function Campfire(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/Campfire 3D Model.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="campfire"
        geometry={nodes.campfire.geometry}
        material={materials.None}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/Campfire 3D Model.glb");
